spring:
  datasource:
    url: jdbc:h2:mem:projecth_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id:
          db_structure_naming_strategy: legacy
  sql:
    init:
      mode: always
  flyway:
    baseline-on-migrate: true

cloud:
  aws:
    region:
      static: eu-central-1
    stack:
      auto: false
    credentials:
      access-key: AKIA3SQGY6M3BWHPSHKC
      secret-key: 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

s3:
  bucket:
    name: projecthackathon

logging:
  file:
    name: /home/ec2-user/backend.log
  logback:
    rollingpolicy:
      max-history: 50
