INSERT INTO CORE_POLITICAL_BELIEVES_ENTITY (ID, ECONOMIC_MARKER, DIPLOMATIC_MARKER, CIVIL_MARKER, SOCIETAL_MARKER)
values (1, 67, 44, 63, 12);
INSERT INTO CORE_POLITICAL_BELIEVES_ENTITY (ID, ECONOMIC_MARKER, DIPLOMATIC_MARKER, CIVIL_MARKER, SOCIETAL_MARKER)
values (2, 22, 42, 67, 99);
INSERT INTO CORE_POLITICAL_BELIEVES_ENTITY (ID, ECONOMIC_MARKER, DIPLOMATIC_MARKER, CIVIL_MARKER, SOCIETAL_MARKER)
values (3, 42, 46, 44, 1);
INSERT INTO CORE_POLITICAL_BELIEVES_ENTITY (ID, ECONOMIC_MARKER, DIPLOMATIC_MARKER, CIVIL_MARKER, SOCIETAL_MARKER)
values (4, 1, 34, 88, 23);
INSERT INTO CORE_POLITICAL_BELIEVES_ENTITY (ID, ECONOMIC_MARKER, DIPLOMATIC_MARKER, CIVIL_MARKER, SOCIETAL_MARKER)
values (5, 25, 99, 100, 4);