INSERT INTO EVENT_ENTITY (ID, NAME, POLITICIAN_ENTITY_ID)
values (1, 'President Election', 1);
INSERT INTO EVENT_ENTITY (ID, NAME, POLITICIAN_ENTITY_ID)
values (2, 'President Election', 2);
INSERT INTO EVENT_ENTITY (ID, NAME, POLITICIAN_ENTITY_ID)
values (3, 'Local Election', 3);
INSERT INTO EVENT_ENTITY (ID, NAME, POLITICIAN_ENTITY_ID)
values (4, 'Local Election', 4);
INSERT INTO EVENT_ENTITY (ID, NAME, POLITICIAN_ENTITY_ID)
values (5, 'President Election', 5);